name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        device: [mark-one, mark-two-sdcard, mark-two-spi]
    
    steps:

    - name: Set up Go 1.12 for ${{ matrix.device }}
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        go get -v github.com/mattn/goveralls
        ls -la $GOPATH/bin/
        GOBIN=$(pwd) go install -v github.com/mattn/goveralls
        ls -la $GOPATH/bin/
        ls -la

    - name: Build
      run: go build -v .
    
    - name: Test
      run: go test -v

    - name: Coveralls (bare)
      run: goveralls -service=github-actions
    
