name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    
    steps:

    - name: Set up
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go version
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        go get -v -d github.com/mattn/goveralls
        cd ~/go/src/github.com/mattn/goveralls
        git checkout tags/v0.0.2
        GOBIN=$(pwd) go install -v github.com/mattn/goveralls

    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: |
        go test -covermode count -coverprofile cover.out
        ./goveralls -v -service github-actions -repotoken ${{ secrets.coveralls }} -coverprofile cover.out
      
    - name: Benchmark
      run: go test -test.run Benchmark -cpu 1 -bench .
