name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      CODE: ~/go/src/github.com/eduncan911/github-actions
    
    steps:

    - name: Set up
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code the Go-Way
      run: |
        env
        pwd
        mkdir -p ~/go/src/github.com/${GITHUB_ACTOR}/
        ls -la ~/go/src/github.com/
        ls -la ~/go/src/github.com/eduncan911/
        cp -r $(pwd) ~/go/src/github.com/${GITHUB_ACTOR}/

    - name: Get dependencies
      run: |
        cd ${CODE}
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        go get -v github.com/mattn/goveralls
        go install -v github.com/mattn/goveralls

    - name: Build
      run: |
        cd ${CODE}
        go build -v ./...
    
    - name: Test
      run: |
        cd ${CODE}
        go test -covermode count -coverprofile cover.out
        ~/go/bin/goveralls -v -service github-actions -repotoken=${{ secrets.coveralls }} -coverprofile=cover.out
      
    - name: Benchmark
      run: |
        cd ${CODE}
        go test -test.run Benchmark -cpu 1 -bench .
