name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      CODE: github.com/eduncan911
      REPO: github-actions
    
    steps:

    - name: Set up
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code the Go-Way
      run: |
        env
        mkdir -p ~/go/src/${CODE}
        cd ..
        ls -la
        mv ${REPO} ~/go/src/${CODE}

    - name: Get dependencies
      run: |
        cd ~/go/src/${CODE}/${REPO}
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        go get -v github.com/mattn/goveralls
        go install -v github.com/mattn/goveralls

    - name: Build
      run: |
        cd ~/go/src/${CODE}/${REPO}
        go build -v ./...
    
    - name: Test
      run: |
        cd ~/go/src/${CODE}/${REPO}
        go test -covermode count -coverprofile cover.out
        ~/go/bin/goveralls -v -service github-actions -repotoken=${{ secrets.coveralls }} -coverprofile=cover.out
      
    - name: Benchmark
      run: |
        cd ~/go/src/${CODE}/${REPO}
        go test -test.run Benchmark -cpu 1 -bench .
